<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-DJNFK38" failures="1" tests="8" name="D:/Softwae Testing ccjuly2024/selenium/actitime-automation/src/test/java/com/actitime_automation/jan_07_2025/ReportsEx1.java" time="0.066" errors="0" timestamp="2025-02-04T19:46:30 IST">
  <testcase classname="com.actitime_automation.jan_07_2025.ReportsEx1" name="UpdateCustomer" time="0.016"/>
  <testcase classname="com.actitime_automation.jan_07_2025.ReportsEx1" name="CreateCustomer" time="0.0">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at com.actitime_automation.jan_07_2025.ReportsEx1.CreateCustomer(ReportsEx1.java:15)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
    </failure>
  </testcase> <!-- CreateCustomer -->
  <testcase classname="com.actitime_automation.jan_07_2025.ReportsEx1" name="DeleteCustomer" time="0.0"/>
  <testcase classname="com.actitime_automation.jan_07_2025.ReportsEx1" name="updateCustomer" time="0.0"/>
  <testcase classname="com.actitime_automation.jan_07_2025.ReportsEx1" name="createCustomer" time="0.0"/>
  <testcase classname="com.actitime_automation.jan_07_2025.ReportsEx1" name="deleteCustomer" time="0.0"/>
  <testcase classname="com.actitime_automation.jan_07_2025.ReportsEx1" name="login" time="0.016"/>
  <testcase classname="com.actitime_automation.jan_07_2025.ReportsEx1" name="logout" time="0.0"/>
</testsuite> <!-- D:/Softwae Testing ccjuly2024/selenium/actitime-automation/src/test/java/com/actitime_automation/jan_07_2025/ReportsEx1.java -->
